Vue.component("we-look", {
    template: // html
    `
    <div class="we-look">
        <div class="container-fluid look-bg">
            <div class="row">
                <div class="col-12 title">
                    <h2>¿QUÉ BUSCAMOS?</h2>
                </div>
                <div class="col-12 content">
                    <p class="mt-2">BUSCAMOS MARCAS INDEPENDIENTES CON PRODUCTOS NO CONVENCIONALES QUE QUIERAN
                    ENRIQUECER LA VIDA DE LAS PERSONAS CON PRODUCTOS LLENOS DE COLOR Y CREATIVIDAD.
                    ENRIQUECER LA VIDA DE LAS PERSONAS CON PRODUCTOS LLENOS DE COLOR Y CREATIVIDAD.</p>
                    <p>BUSCAMOS QUE LOS PARTICIPANTES Y SUS PRODUCTOS SE ALINEEN CON EL CONCEPTO DE LA EDICIÓN:</p>
                    <p><span>ORNAMENTAR CUERPO, ALMA, MENTE Y ESPACIO</span></p>
                    <p>ESPERAMOS LA PARTICIPACIÓN DE EXPOSITORES DE DIFERENTES CATEGORÍAS. HABRÁ UN LÍMITE DE 2 EXPOSITORES POR SUBCATEGORIÍA<span>*</span> CON EL FIN DE AGREGAR EL MÁXIMO VALOR TANTO A LOS EXPOSITORES, COMO A LOS VISITANTES COMPRADORES.</p>
                    <p>POR ESTA RAZÓN LA SELECCIÓN DE MARCAS Y PRODUCTOS HA SIDO MUY RIGUROSA EN CUANTO AL
                    FACTOR DIFERENCIAL DE CADA EXPOSITOR PARA QUE PUEDAN CONVIVIR SIN COMPETIR, SE AGREGUEN
                    VALOR ENTRE SÍ Y SE PUEDAN GENERAR COLABORACIONES FUTURAS.</p>
                    <p><span>PARA TENER EN CUENTA:</span></p>
                    <p>ALGUNAS DE LAS MARCAS ASISTIRÁN CON PRODUCTOS SELECCIONADOS CON EL FIN DE GENERAR MAYORCOHERENCIA CON EL CONCEPTO.</p>
                    <p>PUEDEN PARTICIPAR TANTO PERSONAS NATURALES COMO EMPRESAS.</p>
                    <p>SI ERES UN EXPOSITOR CON UNA MARCA DE ALIMENTOS Y BEBIDAS PODRÁS PARTICIPAR SIEMPRE Y
                    CUANDO TUS PRODUCTOS NO NECESITEN REFRIGERACIÓN NI PREPARACIÓN EN EL INSTANTE.</p>
                    <p><span>*EJEMPLO:</span> CATEGORÍA PRINCIPAL: ACCESORIOS. SUBCATEGORÍA 1: PAÑOLETAS ESTAMPADAS. SUBCATEGORÍA 2: CORDONES PARA GAFAS.  SUBCATEGORÍA 2: CORDONES PARA GAFAS</p>
                </div>
            </div>
        </div>
    </div>
    `
})